# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v3 or later

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f12be1ebaa5351c1fc76472de98db2c3446c8253  # frozen: v0.16.10
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell
        args: ["--check-hidden"]
