# Copyright (C) 2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v3 or later

name: Enforce that copies of --help output are in sync

on:
- pull_request
- push

jobs:
  run_pre_commit:
    name: Check if copies of --help output are in sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python 3.14
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: 3.14

      - name: Install build dependencies
        run: |
          sudo apt-get install --no-install-recommends -y help2man

      - name: Install delete-merged-branches entry point script
        run: |-
          pip install \
            --disable-pip-version-check \
            --user \
            --no-warn-script-location \
            .
          echo "PATH=${HOME}/.local/bin:${PATH}" >> "${GITHUB_ENV}"

      - name: Check if the man page is in sync with --help output
        run: |-
          rm git-{delete-merged-branches,dmb}.1  # to enforce a diff for the generator to remove
          ./sync-manpages-with-help-output.sh
          git diff --exit-code -- git-{delete-merged-branches,dmb}.1
